version: "3.9"

services:
  s3:
    volumes:
      - ./s3-data/:/data/
    ports:
      - 9001:9001

  ftp:
    volumes:
      - ./ftp-data/:/home/reolink/
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

  mysql:
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - 8082:80

  forester:
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      DB_LOGGING_ENABLED: 'true'
    working_dir: /www
    command: /bin/sh -c "npm install && npm start"
